# Generated by Django 5.2.9 on 2026-01-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_size', models.IntegerField(choices=[(5, 'Beginner (5x5)'), (6, 'Medium (6x6)'), (8, 'Hard (8x8)')], default=5)),
                ('level_number', models.IntegerField()),
                ('dot_configuration', models.JSONField(help_text='Paste your JSON dot config here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['grid_size', 'level_number'],
                'unique_together': {('grid_size', 'level_number')},
            },
        ),
    ]
